### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by vidimus** [strategywizard/ExpeditionToTerrorRepository#1]
Hello, @strategywizard 

An user from a Spanish Valkyrie Telegram group wants to translate this scenario into Spanish. Could he start with the translation?

**Comment by strategywizard** [comment]
Hi, Vidimus.

That would be great.  The more people that get to enjoy it, the better!

**Comment by vidimus** [comment]
Hello, @strategywizard .

My colleague has finished the translation. He's now testing and proof reading. I will warn you when the file is ready.

**Comment by vidimus** [comment]
Hello, @strategywizard 

The "Expedition to terror" Spanish version is here:

[Localization.Spanish.txt](https://github.com/strategywizard/ExpeditionToTerrorRepository/files/5287196/Localization.Spanish.txt)

**Comment by strategywizard** [comment]
Hi Vidimus,
Somebody posted a review of Expedition to Terror saying "hay una busqueda en una de las vasijas no traducida"
Google translate leads me to believe that this means something wasn't translated into Spanish.
Strategywizard
    On Saturday, September 26, 2020, 02:13:45 PM CDT, vidimus <notifications@github.com> wrote:  
 
 


Hello, @strategywizard

The "Expedition to terror" Spanish version is here:

Localization.Spanish.txt

**Comment by vidimus** [comment]
Hello, @strategywizard 

Thanks for the information. Yes, the messages says that there's a untranslated text entry about one of the temple jars. That's weird, because we check it several time. Anyway, I will review it and I will send you a new file next week.

**Comment by strategywizard** [comment]
Hi Vidimus,
Thanks a lot!  There are 5 possible events, but only 3 jars.  Perhaps your test runs never stumbled on one of the potential events.
Strategywizard
    On Friday, October 2, 2020, 12:48:21 PM CDT, vidimus <notifications@github.com> wrote:  
 
 


Hello, @strategywizard

Thanks for the information. Yes, the messages says that there's a untranslated text entry about one of the temple jars. That's weird, because we check it several time. Anyway, I will review it and I will send you a new file next week.

**Comment by vidimus** [comment]
Hi, @strategywizard .

I have figured something like that. Thanks for the information. It's quite common that issue in some scenarios.

By the way, do you have plans for futher updatings of "Book a room for a murder"? Because I would like to translate it into Spanish as well. I find your scenarios quite interesting and enjoyable.

**Comment by strategywizard** [comment]
Hi Vidimus,
I'm glad you enjoyed my scenarios!
As of right now, I don't have any updates planned for "Book a Room for Murder."  Unless somebody finds a significant issue, it will likely stay as it is.
You are more than welcome to start translating it.
Strategywizard

    On Saturday, October 3, 2020, 03:30:45 AM CDT, vidimus <notifications@github.com> wrote:  
 
 


Hi, @strategywizard .

I have figured something like that. Thanks for the information. It's quite common that issue in some scenarios.

By the way, do you have plans for futher updatings of "Book a room for a murder"? Because I would like to translate it into Spanish as well. I found your scenarios quite interesting and enjoyable.

**Comment by vidimus** [comment]
Great, @strategywizard . I will contact you when I start the translation.

**Comment by vidimus** [comment]
Hello, @strategywizard 

I've fixed a minor problem with the Spanish translation: there was a sentence that remained untranslated and it appeared in English.
Here's the new file. Could you please update your scenario with this new version?

(File deleted)

**Comment by strategywizard** [comment]
Hi Vidimus,
Thanks for the updated translation.  I think I updated it properly, but let me know if there are any issues.
Strategywizard 

    On Friday, February 12, 2021, 04:59:04 PM CST, vidimus <notifications@github.com> wrote:  
 
 


Hello, @strategywizard

I've fixed a minor problem with the Spanish translation: there was a sentence that remained untranslated and it appeared in English.
Here's the new file. Could you please update your scenario with this new version?

Localization.Spanish.txt

**Comment by vidimus** [comment]
Hello, @strategywizard 

I'm afraid not. It seems there's a missing part of the translation text (the headline). I will redo it (not sure what has happened). Scenario is now unplayable in Spanish.

Please, update the scenario with this file:
[Localization.Spanish.txt](https://github.com/strategywizard/ExpeditionToTerrorRepository/files/5976284/Localization.Spanish.txt)
